### ISSUE TITLE
fbas_analyzer crashes on current stellarbeat data

### ISSUE THREAD

**Issue by nano-o** [trudi-group/fbas_analyzer#6]
Following "Usage as tools" in the README, I ran `scripts/get_latest_stellarbeat_data.sh` (step 5) and then `target/release/fbas_analyzer test_data/stellarbeat_nodes_2023-09-13.json --merge-by-org test_data/stellarbeat_organizations_2023-09-13.json --ignore-inactive-nodes -apdS --only-core-nodes`  (as suggested in the output of the previous command). This results in:
```
Reading FBAS JSON from file...
thread 'main' panicked at 'Error parsing FBAS JSON: Error("invalid type: null, expected struct RawQuorumSet", line: 1, column: 50659)', src/io/core_types.rs:47:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by marfl** [comment]
Thanks for raising this! https://github.com/trudi-group/fbas_analyzer/commit/2c44ba49a0e0f13265d6cb0ba244504021006dc5 contains the fix. LMK if you encounter anything else!
